### ISSUE TITLE
Not compatible with SvelteKit/vite

### ISSUE THREAD

**Issue by PlkMarudny** [svar-widgets/core#1]
Not compatible with SvelteKit. In SSR mode produces:

```
[vite] Error when evaluating SSR module /node_modules/.pnpm/@wx+svelte-core@1.1.3/node_modules/@wx/svelte-core/src/Locale.svelte: failed to import "@wx/core-locales"
```
With SSR mode disabled,

```
Cannot find module '@wx/svelte-core' or its corresponding type declarations.
```

**Comment by mkozhukh** [comment]
Yep, I can confirm that prior version 1.1.4, svelte-core library was incompatible with svelte-kit ( which uses typescript under hood ) 
Latest version (1.1.4) works fine in default svelte-kit template.
