### ISSUE TITLE
Question: Are you planning to introduce a grid?

### ISSUE THREAD

**Issue by boustanihani** [svar-widgets/core#2]
Question: Are you planning to introduce a grid and maybe also css breakpoints (Like XL, L, M, S, XS) so we can control how the layout behaves on all screens?

**Comment by Zwillinge** [comment]
Hello, 

Rather not, as we assume that users create layouts themselves and arrange them with CSS directly or use the favourite CSS framework. This means more flexibility. 

In future in case of strong demand we can add a small lib for these needs, but it is likely to be just flex box wrappers.

**Comment by boustanihani** [comment]
Thank you
