### ISSUE TITLE
Select: doesn't have a slot like docs show

### ISSUE THREAD

**Issue by adam-lynch** [svar-widgets/core#6]
The [Select documentation](https://docs.svar.dev/svelte/core/select/) has code examples which pass a slot to `Select`, but it doesn't actually accept any slot; see https://github.com/svar-widgets/core/blob/main/src/common/Select.svelte

**Comment by Zwillinge** [comment]
Thank you for pointing, we will correct Select documentation. It is based on a simple HTML select control, while Richselect allows providing option template as a slot.
